// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59LE9kzPv0xqlqCGnC5l4xUS7eLShTTs',
    appId: '1:426857757301:web:0634a16e0d3d217d1a963c',
    messagingSenderId: '426857757301',
    projectId: 'second-srving',
    authDomain: 'second-srving.firebaseapp.com',
    storageBucket: 'second-srving.firebasestorage.app',
    measurementId: 'G-3F273CP9ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SJk9T6JD_9ACpNYJnSPZTkz2zwOYo0s',
    appId: '1:426857757301:android:6a374445f79ced471a963c',
    messagingSenderId: '426857757301',
    projectId: 'second-srving',
    storageBucket: 'second-srving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAot93W-3RFvytdeFyel60_EF2n5CYzKa0',
    appId: '1:426857757301:ios:c05e7be471826df81a963c',
    messagingSenderId: '426857757301',
    projectId: 'second-srving',
    storageBucket: 'second-srving.firebasestorage.app',
    iosBundleId: 'com.example.secondServing',
  );
}
